COLECCION_SENTINEL1 = "COPERNICUS/S1_GRD"
MODO_INSTRUMENTO = "IW"
POLARIZACIONES = ("VV", "VH")
RESOLUCION_METROS = 10
BANDAS_EXPORTACION = ("VV", "VH", "angle")
ORBITAS_VALIDAS = ("AMBAS", "ASCENDENTE", "DESCENDENTE")
